# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180113_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpquestions',
            name='name',
            field=models.CharField(blank=True, db_column='Name (Optional)', max_length=100, null=True),
        ),
    ]
